# Generated by Django 3.0.5 on 2021-05-11 09:26

import Applications.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('mobile', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(blank=True)),
                ('age', models.SmallIntegerField(blank=True)),
                ('gender', models.TextField(blank=True)),
                ('annual_income', models.IntegerField(blank=True)),
                ('members', djongo.models.fields.ArrayField(model_container=Applications.models.Member, blank=True)),
                ('source', models.TextField(blank=True)),
                ('destination', models.TextField(blank=True)),
                ('reason', models.TextField(blank=True)),
                ('vehicle', models.TextField(blank=True)),
                ('duration', models.IntegerField(blank=True)),
                ('photo', models.TextField()),
                ('aadhar', models.TextField(blank=True)),
                ('pan', models.TextField(blank=True)),
                ('driving_license', models.TextField(blank=True)),
                ('voter_id', models.TextField(blank=True)),
                ('application_type', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('elicense', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('application_date', models.DateTimeField(auto_now_add=True, editable=False)),
            ],
        ),
    ]
