# Generated by Django 3.0.5 on 2021-05-13 07:27

import StakeHolders.models
from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('StakeHolders', '0002_lawyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connect',
            name='conversation',
            field=djongo.models.fields.ArrayField(blank=True, model_container=StakeHolders.models.Message),
        ),
    ]
