# Generated by Django 3.0.5 on 2021-05-13 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StakeHolders', '0003_auto_20210513_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connect',
            name='lawyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lawyer', to='StakeHolders.Lawyer'),
        ),
    ]
