# Generated by Django 3.0.5 on 2021-05-13 10:05

import StakeHolders.models
from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('StakeHolders', '0004_auto_20210513_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connect',
            name='conversation',
            field=djongo.models.fields.ArrayField(model_container=StakeHolders.models.Message),
        ),
    ]
